import dog from "../../../assets/images/RecommendPage/dog.png";
import pension from "../../../assets/images/RecommendPage/pension.png";
import river from "../../../assets/images/RecommendPage/river.png";

export const scrollDummyImg = [
  {
    id: 1,
    image: river,
    category: "여행지",
    title: "river",
    date: "2022.08.26~",
    alt: "한강이미지",
    textTitle: "한강 달빛 야시장",
    textLine1: "한강에서 즐기는 축제!",
    textLine2: "3년만에 재개장하는 야시장에서 다양하게 즐겨보세요.",
    link: "/",
  },
  {
    id: 2,
    image: dog,
    category: "여행지",
    title: "dog",
    date: "2022.08.26~",
    alt: "강아지산책이미지",
    textTitle: "생태정원 & 카페 문화박물관",
    textLine1: "제주 '숨도'에서 귀한 경험을 해보세요!",
    textLine2: "다양한 포토존을 통해 반려동물과 추억을 쌓아요",
    link: "/",
  },
  {
    id: 3,
    image: pension,
    category: "숙소",
    title: "pension",
    date: "2022.08.26~",
    alt: "펜션이미지",
    textTitle: "경주 독채 펜션'오늘도 너와'",
    textLine1: "우리들의 오롯한 쉼이 되어주는 ‘오늘도 너와’에서",
    textLine2: "잊지못할 경험을 해보세요",
    link: "/",
  },
  {
    id: 4,
    image: river,
    category: "여행지",
    title: "river",
    date: "2022.08.26~",
    alt: "한강이미지",
    textTitle: "한강 달빛 야시장2",
    textLine1: "한강에서 즐기는 축제!",
    textLine2: "3년만에 재개장하는 야시장에서 다양하게 즐겨보세요.",
    link: "/",
  },
  {
    id: 5,
    image: dog,
    category: "여행지",
    title: "dog",
    date: "2022.08.26~",
    alt: "강아지산책이미지",
    textTitle: "생태정원 & 카페 문화박물관2",
    textLine1: "제주 '숨도'에서 귀한 경험을 해보세요!",
    textLine2: "다양한 포토존을 통해 반려동물과 추억을 쌓아요",
    link: "/",
  },
  {
    id: 6,
    image: pension,
    category: "숙소",
    title: "pension",
    date: "2022.08.26~",
    alt: "펜션이미지",
    textTitle: "경주 독채 펜션'오늘도 너와'2",
    textLine1: "우리들의 오롯한 쉼이 되어주는 ‘오늘도 너와’에서",
    textLine2: "잊지못할 경험을 해보세요",
    link: "/",
  },
];
